# Generated by Django 5.2.7 on 2026-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add_ai_moderation_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_moderation_status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('PROCESSING', 'AI đang xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', help_text='Trạng thái AI kiểm duyệt: PENDING=chờ, PROCESSING=AI đang xử lý, APPROVED=đã duyệt, REJECTED=từ chối', max_length=20),
        ),
    ]
