# Generated by Django 5.2.7 on 2026-04-08 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('PROTEIN', 'Đạm (Thịt, cá, trứng...)'), ('CARB', 'Tinh bột (Gạo, mì, bún...)'), ('VEG', 'Rau củ'), ('SPICE', 'Gia vị đặc trưng (Sả, ớt, hồi...)'), ('STAPLE', 'Gia vị cơ bản (Muối, đường, dầu...)'), ('OTHER', 'Khác')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
    ]
