# Generated by Django 5.2.7 on 2026-05-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Đơn vị',
                'verbose_name_plural': 'Đơn vị',
                'db_table': 'units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allowed_units',
            field=models.ManyToManyField(blank=True, related_name='used_in_ingredients', to='ingredients.unit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_ingredients', to='ingredients.unit'),
        ),
    ]
