# Generated by Django 5.2.7 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_seed_units'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone NULL;',
                    reverse_sql='ALTER TABLE ingredients DROP COLUMN IF EXISTS deleted_at;',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;',
                    reverse_sql='ALTER TABLE ingredients DROP COLUMN IF EXISTS is_deleted;',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ingredient',
                    name='deleted_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='ingredient',
                    name='is_deleted',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
