# Generated by Django 5.2.7 on 2026-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_deleted_at_ingredient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
