# Generated by Django 5.2.7 on 2026-04-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantry',
            options={'ordering': ['ingredient__name'], 'verbose_name': 'Tủ lạnh số', 'verbose_name_plural': 'Tủ lạnh số'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danh sách đi chợ', 'verbose_name_plural': 'Danh sách đi chợ'},
        ),
    ]
