# Generated by Django 5.2.7 on 2026-05-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_favorites',
            field=models.BooleanField(default=False, help_text='True nếu đây là collection Yêu thích mặc định, không thể xóa'),
        ),
    ]
