# Generated by Django 5.2.7 on 2026-05-09 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('REPORT_PROCESSED', 'Báo cáo đã xử lý'), ('WARNING', 'Cảnh cáo')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, help_text='Dữ liệu bổ sung dạng JSON', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('recipe', 'Công thức'), ('review', 'Đánh giá'), ('user', 'Người dùng')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('WRONG_CONTENT', 'Nội dung sai'), ('HARASSMENT', 'Quấy rối'), ('COPYRIGHT', 'Vi phạm bản quyền'), ('INAPPROPRIATE', 'Không phù hợp')], max_length=20)),
                ('additional_info', models.TextField(blank=True, default='', help_text='Thông tin bổ sung từ người báo cáo')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('REVIEWED', 'Đã duyệt'), ('DISMISSED', 'Bỏ qua')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter', 'target_type', 'target_id'], name='rep_rtl_tid_idx'), models.Index(fields=['status'], name='rep_status_idx')],
            },
        ),
    ]
