# Generated by Django 5.2.7 on 2026-05-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_id',
            field=models.CharField(help_text='ID của đối tượng bị report (UUID cho Recipe/User, integer cho Review)', max_length=36),
        ),
    ]
