# Generated by Django 5.2.7 on 2026-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REPORT_PROCESSED', 'Báo cáo đã xử lý'), ('WARNING', 'Cảnh cáo'), ('INGREDIENT_REJECTED', 'Nguyên liệu bị từ chối')], max_length=20),
        ),
    ]
