# Generated by Django 5.2.7 on 2026-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, help_text='Google OAuth subject ID (sub claim)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text='Whether user logged in via Google at least once'),
        ),
    ]
